server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: jongmin
    password: '0000'

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
      security:    oauth2:      client:        registration:
          facebook:
            client-id: 630434121750256
            client-secret: 325939c1a772b97d3aeed959982c1697
            scope:
            - email
            - public_profile          google:
            client-id: 575523110904-a6d9m9ucps059pair0nm31358jgpmm4e.apps.googleusercontent.com
            client-secret: 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
            scope:            - email
            - profile
          naver:
            client-id: XvMW2XJTRuKVXEJ7ANYJ
            client-secret: 6QBknpHrSb
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            
        provider:          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            
            